### ISSUE TITLE
Saved image actually can not be opened

### ISSUE THREAD

**Issue by jinfagang** [esimov/pigo#1]
Like this image ![link](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528295391389&di=5563310898112d183045563ff63c9023&imgtype=0&src=http%3A%2F%2Fwww.th7.cn%2Fd%2Ffile%2Fp%2F2017%2F02%2F11%2F65eeeffd4e245488bd25376db5c66b10.jpg)

It processed but can not open

**Comment by esimov** [comment]
What do you mean by "it cannot be opened"? Can you detail it?

**Comment by jinfagang** [comment]
```
./pigo -in in.jpg -out out.jpg -cf data/facefinder
```
the saved image which is out.jpg can not be opened (Platform Ubuntu18.04, you can download this image and try it.)

**Comment by mbrlabs** [comment]
@jinfagang The actual output image format is png, not jpg (like the extension in the command would suggest). Most Linux image viewers can't handle that and assume the file is corrupted. 
If you rename out.jpg to out.png you can open it.

**Comment by jinfagang** [comment]
@mbrlabs Thanks, I will try

**Comment by esimov** [comment]
@jinfagang i've extended the library to support different exported image file types. Please check it now.
