### ISSUE TITLE
json export of face coordinates is empty

### ISSUE THREAD

**Issue by foobargeez** [esimov/pigo#13]
I got the face detection working (thanks for your help in https://github.com/esimov/pigo/issues/12) but when I specify `-json`, I see output.json getting created but empty.

`./pigo -cf data/facefinder -in in.jpg -out out.png -angle=0.3 -json`

**Comment by foobargeez** [comment]
Also, is there anyway to just export json and not the output image?  I plan to use this programmatically to get the face coordinates and see if the face/image is 90/180/270 rotated and if so, I will have to rotate it.  I need to run this against thousands of images on a daily basis and generating an output image is not a requirement for me as I only will end up deleting it.

**Comment by esimov** [comment]
Regarding the first issue: you should make a git pull again or reinstall the package, since this issue has been fixed here: https://github.com/esimov/pigo/commit/858f119a0cd053c3eb19eee5353350d8c61ae5fe.

As of the second question, the answer is no.

**Comment by foobargeez** [comment]
Thanks.  The json export of face coords is working.  It seems I will have to keep running pigo in a loop from angle values 0.1 to 1.0 until I find a face or until I exhaust all angle values .. that's a lot of resources (including elapsed time) as my requirement is to run against hundreds, if not thousands, of images on a daily basis.  I will keep monitoring this project and see if it fits my use case in future versions.

Good luck!
