### ISSUE TITLE
The use of log.Fatal

### ISSUE THREAD

**Issue by bep** [esimov/pigo#2]
First, thanks for this, this is very much appreciated, and the code looks solid.

I have one small request, which I think is needed for this to be used as a library. And that is to replace the `log.Fatal` (which does an ´os.Exit` I don't think is even possible to catch in a client):

https://github.com/esimov/pigo/blob/master/core/pigo.go#L67

I would suggest just returning an error. This may be "this should never happen errors", and then a panic may be in order.

**Comment by esimov** [comment]
@bep i have replaced the log message with error return. I also updated the package files if needed.
