### ISSUE TITLE
Question: Facial/Identity Recogntition possible?

### ISSUE THREAD

**Issue by prologic** [esimov/pigo#23]
Would it be possible to extend this library or use it as-is to perform facial recognition and thus identity of persons in images? (as opposed to face detection)

**Comment by esimov** [comment]
No, it's not possible. The library does not support facial recognition.

**Comment by esimov** [comment]
Currently yes, because Pigo is using pretrained data (cascades) for face, eyes and facial landmark points detection. In this sense Pigo is much like a computer vision than a machine learning library. 

At the moment i'm not considering extending the library in that direction, but who knows maybe in the future.

**Comment by olekukonko** [comment]
Now that `pigo` supports `Facial landmark points detection`,  Is it not possible to save the face’s attributes and vector and then use Euclidean distance to implement facial recognition?

**Comment by olekukonko** [comment]
@esimov  what do you think ?

**Comment by esimov** [comment]
Interesting point of view, but from my opinion the difficulty of this approach is that the face recognition outcome always have to be independent of way the person is displayed regardless of image dimension, the face angle, the mouth position etc. which means I don't foreseen this approach to provide viable results without involving neural networks.

**Comment by olekukonko** [comment]
@esimov  it might interest you that this approach has been used before with the [meaningful result]( https://towardsdatascience.com/how-to-build-a-face-detection-and-recognition-system-f5c2cdfbeb8c ) however i agree with you 100% that neural networks is the way to go.

**Comment by esimov** [comment]
Thanks for the link. Dlib by default supports face recognition and as the article states they are using Dlib on their application. But anyway thanks for coming up with this idea, it's worth to make some research on this topic. Any PR's, feedback, articles are welcome.

**Comment by olekukonko** [comment]
@esimov a pure `go` facial recognition is definitely gold.  I would definitely keep discussing this with you. Well done for the excellent work.

**Comment by olekukonko** [comment]
Any update on this?
