### ISSUE TITLE
Q&A article on pigo

### ISSUE THREAD

**Issue by brucou** [esimov/pigo#26]
Hi Endre (@esimov),

We would like to write a short piece about Pigo for our audience of developers and would like to do a Q&A with you. Article would be published on infoq.com. Last article on wasm was about a [desktop game editor](https://www.infoq.com/articles/wasm-game-editor-port/?itm_source=articles_about_WebAssembly&itm_medium=link&itm_campaign=WebAssembly) ported to WebAssembly. Let me know if that is of any interest to you.

**Comment by esimov** [comment]
Hello @brucou yes, i'm interested. We can continue the discussion trough my personal [email](mailto:esimov@gmail.com). I will close this ticket since is not related to any bugs or issues. So please give me more details on email.
