### ISSUE TITLE
JSON output containing face box coordinates doesn't match with faces

### ISSUE THREAD

**Issue by Bekassyl** [esimov/pigo#29]
In code I can see that DrawRectangles and Face Coordinates have the same input, but it turns out that the coordinates doesn't match face boxes. Is it a bug? Or I don't understand something?

**Comment by esimov** [comment]
I've checked the issue you have reported, but i don't see any misbehavior in the resulted json output. Can you give me an example? The `Min` and `Max` values represents exactly the rectangle detected by the face detector.

**Comment by esimov** [comment]
Since I haven't received any feedback i'm closing this issue. You can reopen anytime.

**Comment by esimov** [comment]
The code has been refactored. Check this issue #33.
