### ISSUE TITLE
Eye/Facial Coordinates in JSON?

### ISSUE THREAD

**Issue by rgvxlens** [esimov/pigo#33]
Hi there, is it possible to print/output the Facial Coordinates/Pupil Localization pointers in the JSON file with -json itself? Or any work around for the same?

or any other way to print the exact coordinates of the pupils or the other facial features?

**Comment by esimov** [comment]
Currently only the face coordinates could be exported into a JSON file, but this can be extended to support the pupil and facial coordinates.

**Comment by rgvxlens** [comment]
Thanks for the your quick response! 

But can this still be done if I create an API for the same or a Python program? Just need to output the coordinates somewhere.

**Comment by esimov** [comment]
You mean would you like such a feature to be included into the library? If that's what you want I can take care of it.

**Comment by rgvxlens** [comment]
Would be awesome! or maybe a way to just get specific features in the JSON? Both would be helpful, or whatever is possible according to you.

**Comment by esimov** [comment]
@rgvxlens i've extended the json marshalizer to include the pupils/eyes localization and landmark points detection coordinates. Currently the json export is looking something like this:

```bash
[{
	"face": {
		"x": 129,
		"y": 131,
		"size": 158
	},
	"eyes": [{
		"x": 116,
		"y": 107,
		"size": 12
	}, {
		"x": 114,
		"y": 162,
		"size": 13
	}],
	"landmark_points": [{
		"x": 103,
		"y": 185,
		"size": 19
	}, {
		"x": 91,
		"y": 168,
		"size": 19
	}, {
		"x": 103,
		"y": 147,
		"size": 19
	}, {
		"x": 115,
		"y": 152,
		"size": 19
	}, {
		"x": 113,
		"y": 175,
		"size": 19
	}, {
		"x": 153,
		"y": 134,
		"size": 19
	}, {
		"x": 184,
		"y": 113,
		"size": 19
	}, {
		"x": 192,
		"y": 133,
		"size": 19
	}, {
		"x": 179,
		"y": 134,
		"size": 19
	}, {
		"x": 183,
		"y": 160,
		"size": 19
	}]
}]
```
You might ignore the size in `eyes` and `landmark_points` since they are not really relevant.

**Comment by rgvxlens** [comment]
What does the size denote here?
For eg here:
	"eyes": [{
		"x": 116,
		"y": 107,
		"size": 12
	}, {
		"x": 114,
		"y": 162,
		"size": 13
	}],

Does the size here denote pupil size?

**Comment by rgvxlens** [comment]
Thanks for this! What does the size in the face denote?

**Comment by esimov** [comment]
The dimension of the detected face region.

**Comment by rgvxlens** [comment]
Alright, i'll give it a look and report back. Thanks a lot and kudos to you for this amazing project.

**Comment by rgvxlens** [comment]
Hey! I had a few questions, I hope you don't mind answering them:

1. Why is my output always like this? 
> [{"Min":{"X":33,"Y":81},"Max":{"X":243,"Y":243}}]

This is the command that I'm running:
`pigo -in /home/rgvx/githubstuff/RedEyeRemover/test.jpeg -out output.jpg -cf /home/rgvx/githubstuff/pigo/cascade/facefinder -mark -pl -plc /home/rgvx/githubstuff/pigo/cascade/puploc  -json`

Is it a problem with the command I'm running?

2. What is the format of the "size" value? Is it in Pixels?

Thanks!

**Comment by esimov** [comment]
Every value in the json file is in pixel format. The `size` value as I mentioned earlier in the thread represents the detected face rectangle size, but since this might be relevant only for the detected face you can ignore on pupil/eyes localization and facial landmark detection, but it's up to you.

**Comment by rgvxlens** [comment]
Oh, thanks! Got it, I'm now looking into calculating/detecting the radius of the eyes with the coordinates that I've obtained.

**Comment by esimov** [comment]
You don't need to calculate the radius of the eyes, you only need to multiply the scale value with a percentage, 0.4 should give you an approximate correct result.

**Comment by rgvxlens** [comment]
That's exactly what I'm looking for. Thank you so much mate! What exactly is that value? Can you give me a bit of a background on that? Just so that I have some background info on that.

**Comment by esimov** [comment]
@rgvxlens i'm really glad that it worked for you! ;)
