### ISSUE TITLE
web example

### ISSUE THREAD

**Issue by gerben-b** [esimov/pigo#35]
Hi,

If I run your web example than I get this error:
2020/04/24 21:51:38 [ERROR] reading next part multipart: NextPart: EOF
I must admit that I don't meet the requirements for this example. My python is python3 and my opencv is 4.2. OS is Ubuntu 20.04LTS.
I tested as follows
1. Run: go run main.go -cf "../../cascade/facefinder"
2. Open URL: localhost:8081/cam in browser
3. Then this error appears
Any ideas? Thanks

**Comment by esimov** [comment]
This demo has been adapted to Python2 only, Python3 is not yet supported, that's why you are getting the above error.

**Comment by gerben-b** [comment]
That is what i thought too. Do you have plans to make a python 3 version? I would like that since python 2 is no longer supported.

**Comment by esimov** [comment]
I might consider it depending on my possibilities, but yes I will take into consideration.

**Comment by gerben-b** [comment]
Thanks, I look forward to that.
