### ISSUE TITLE
github.com/esimov/pigo/webcam does not build

### ISSUE THREAD

**Issue by h8liu** [esimov/pigo#4]
```
# github.com/esimov/pigo/webcam
src/github.com/esimov/pigo/webcam/main.go:127:28: multiple-value pigo.Unpack() in single-value context
```

Found by [smallrepo](https://smallrepo.com).

Build log: https://smallrepo.com/builds/20180607-063653-c1d35e4f

**Comment by esimov** [comment]
I've updated the core API before (https://github.com/esimov/pigo/issues/2), this is why you got the above error. This issue is fixed now.
