### ISSUE TITLE
x / y values are backwards in json output

### ISSUE THREAD

**Issue by garygreen** [esimov/pigo#43]
For some reason the x isn't really x but it's the y value, and vice versa. Weirdly they seem backwards in the json output.

I tested this by opening the image in photoshop and seeing where the x / y sits as compared to the values reported by pigo. They are accurate, just backwards. Unless I've clearly done something nooby 😕

**Comment by esimov** [comment]
@garygreen thanks for notifying this issue. There was another issue someway related to the reported one, regarding the correctness of the detection points written into the json output. This has been also fixed.
