### ISSUE TITLE
Can this be somehow used to smart-detect background image and replace it in realtime?

### ISSUE THREAD

**Issue by s3rj1k** [esimov/pigo#52]
Can this be somehow used to smart-detect background image and replace it in realtime?

**Comment by esimov** [comment]
You want something like what zoom or skype offer? I mean to retain the face unaltered but replace the background with a custom image? I suppose you tried the wasm version...

**Comment by s3rj1k** [comment]
@esimov yea, exactly, did not try anything yet, first thing that came to my mind when I saw this lib, was can I do smart background replacement with it :)

I know it can be done using python, but I like that this is golang lib :)
