### ISSUE TITLE
Adding jaw line facial landmarks

### ISSUE THREAD

**Issue by andrewwormald** [esimov/pigo#53]
Would you be able to explain how you went and generated the facial landmark / density tree files that are used in the implementation of the Fast Localization of Facial Landmark Points? I would be keen to contribute, or ask if you can, the jaw line to the list of supported facial landmarks

**Comment by andrewwormald** [comment]
I see the following in the paper:

>  The learning of the whole
> estimation structure for a single landmark point takes around
> one day on a modern desktop computer with 4 cores and 16
> GB of memory.

**Comment by esimov** [comment]
I didn't generated myself, I've used the density tree files accompanied with the paper. In order to use jaw line, these facial landmark points needs to be trained which currently they are not.
