### ISSUE TITLE
Return bounding box coordinates from command line?

### ISSUE THREAD

**Issue by markreg** [esimov/pigo#7]
Thanks for sharing this awesome project!

Is it possible to get bounding box coordinates outputted to the command line? I'd like to use pigo on my raspberry pi 3 to automatically crop images captured by the raspberry pi camera.

Also, would this work with people who are wearing glasses?

Many thanks!

**Comment by esimov** [comment]
Hey, thanks for the feedback. Yes, it's possible you can take this for reference: https://github.com/esimov/pigo/commit/6dbb9e779c598e4d166536c5f5d7a85c8f0e0955#diff-8d03067e72a00b1307b7c27ee9856710L138. Also the api can detect faces with glasses. Hope it helps, otherwise let me know.

**Comment by markreg** [comment]
Awesome, thanks.
